version: "3"

services:
  level01:
    build: ./cmdi_level1
    container_name: 'cmdi_level01'
    restart: 'unless-stopped'
    ports:
      - "3001:80"
    volumes: 
      - ./cmdi_level1/src/:/var/www/html/
  level02:
    build: ./cmdi_level2
    container_name: 'cmdi_level02'
    restart: 'unless-stopped'
    ports:
      - "3002:80"
    volumes: 
      - ./cmdi_level2/src/:/var/www/html/
networks:
  internet: {}
  no-internet:
    internal: true
